### ISSUE TITLE
Using MediaElement as audio player

### ISSUE THREAD

**Issue by CyberSinh** [unosquare/ffmediaelement#144]
Hi Mario,

I try to play with latest beta Michelob NuGet package and here are the issues I get. 
You can download the sample repro here: 
https://www.dropbox.com/s/t2vpqpg8feltx00/TestWpf1.zip?dl=0

1. 
I sometimes get this exception when I try to open an audio file:
_Une exception non gérée du type 'System.EntryPointNotFoundException' s'est produite dans ffme.common.dll: Could not find the entrypoint for sws_getCachedContext._

This issue seems to happen not only with my custom FFmpeg build, optimized for audio processing only (in "ffmpeg_c" folder) but also with the standard Zeranoe build (in "ffmpeg_z" folder).

2. 
I need to call the Play command twice to start playing file. And if I close the file, I cannot play it again. This is probably the result of misuse of MediaElement control on my part but I would like your opinion.

3.
Could it be possible to use a control lighter than MediaElement for audio playing only: a control which would descend directly from DependencyObject and not from UserControl (which itself descends from Visual, UIElement, FrameworkElement, Control, ContentControl) because no visual control is needed.

4.
The MediaElement has an IsPlaying property. It might be useful to add a native IsPaused property too. What do you think about it?

Thank you very much for this great control.

Regards,

Sylvain

**Comment by mariodivece** [comment]
Ok thanks for the reports.
1. Has been fixed in the latest master commit. Thanks for reporting!
2. This is because setting the source is not a synchronous operation. calling play before the source has been fully opened has no effect. Either handle the MediaOpened event or Set the LoadedBehabior to Play. Example:
```csharp
        public async Task PlayAsync()
        {
            if (mediaElement.IsPlaying || IsPaused)
                await mediaElement.Stop();

            if (mediaElement.Source?.OriginalString != nextMediaPath)
                mediaElement.Source = new Uri(nextMediaPath);

            mediaElement.MediaOpened += MediaElement_MediaOpened;
        }

        private async void MediaElement_MediaOpened(object sender, System.Windows.RoutedEventArgs e)
        {
            mediaElement.MediaOpened -= MediaElement_MediaOpened;
            await mediaElement.Play();
        }
```
3. Use the ffme.common library to implement your own. It contains the MediaEngine class that the Windows WPF control wraps. You can follow very similar patterns as with the WPF control.

4. This is available in my latest master commit. Thanks for the suggestion.
