### ISSUE TITLE
SpeedRatio 4 causes playback issues

### ISSUE THREAD

**Issue by trecoll** [unosquare/ffmediaelement#26]
Hi,

When I set the SpeedRatio to 4, the media will play at 4x speed, for a few seconds but then pause. 

Sending a play command to the player will repeat this process. A SpeedRatio less than 4 does not cause this issue.

Any ideas?

**Comment by mariodivece** [comment]
It's because it is unable to decode the frames fast enough. In reality the decoding logic should skip over 3 frames and then decode the fourth one. It's not how it is working now. I started changing the decoding logic and improving it but I need more spare time to finish it. I am aware of this issue.
