### ISSUE TITLE
Seek before PlayCommand is ignored

### ISSUE THREAD

**Issue by RyanYANG52** [unosquare/ffmediaelement#263]
# Seek before PlayCommand is ignored

*If I set position right before play(), it will ignore the position setting*

## Issue Categories

 - [x] Bug
 - [ ] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information
 - [x] Build From *Master* branch, Commit *f62b31bfb515cb5724957da168c429d42091c6a2*

## Steps to Reproduce

 1. Change PlayCommand code to 
```
            public DelegateCommand PlayCommand
            {
                get
                {
                    if (m_PlayCommand == null)
                        m_PlayCommand = new DelegateCommand(async o => 
                        {
                            Current.MediaElement.Position = TimeSpan.Zero;
                            //await System.Threading.Tasks.Task.Delay(1);
                            await Current.MediaElement.Play();
                        });

                    return m_PlayCommand;
                }
            }
```
 2. Run sample app, play any video, pause, then play
 3. In theory, every time you click play button, it should start from the begining, the result is : player start from previous pause position
4. Uncomment the Task.Delay(1) , it works as expected

**Comment by mariodivece** [comment]
This is by design. Position is a bidirectional dependency property. Setting it only queues the seek action but the Play command clears the seek queue. I do however see the need for the use case where we need to wait for the seek to complete and then perform the play. For this reason, I have added a `Seek` method that is awaitable. Now you should be able to do something like:
```csharp
            public DelegateCommand PlayCommand => m_PlayCommand ??
                (m_PlayCommand = new DelegateCommand(async o =>
                {
                    await Current.MediaElement.Seek(TimeSpan.Zero);
                    await Current.MediaElement.Play();
                }));
```

I appreciate your input! Feel free to add more comments if the issue persists and I'll reopen this.
