### ISSUE TITLE
The calling thread cannot access this object because a different thread owns it.

### ISSUE THREAD

**Issue by shamsadzaman** [unosquare/ffmediaelement#321]
# The calling thread cannot access this object because a different thread owns it.

*This is a weird bug that got introduced after I updated my nuget package to 4.0.270. I was getting the "...thread cannot access..." exception when I was assigning the source from code behind. But it happened only from my application, when I created a sample application and try to reproduce the bug it worked fine.

After debugging I found this stack trace:
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at System.Windows.Interactivity.TriggerBase.get_Actions()
   at System.Windows.Interactivity.TriggerBase.InvokeActions(Object parameter)
   at System.Windows.Interactivity.EventTriggerBase.OnEvent(EventArgs eventArgs)
   at System.Windows.Interactivity.EventTriggerBase.OnEventImpl(Object sender, EventArgs eventArgs)
   at Unosquare.FFME.MediaElement.RaiseMediaInitializingEvent(ContainerConfiguration config, String url)
   at Unosquare.FFME.Platform.WindowsMediaConnector.OnMediaInitializing(MediaEngine sender, ContainerConfiguration config, String url)
   at Unosquare.FFME.MediaEngine.SendOnMediaInitializing(ContainerConfiguration config, String url)
   at Unosquare.FFME.Commands.DirectOpenCommand.PerformActions()

Pulled the code from Master (791a1ec954d762647) and added Dispatcher.CurrentDispatcher.BeginInvoke() inside WindowsMediaConnector.OnMediaInitializing() and that fixed the issue. I also had to do this for WindowsMediaConnector.OnMediaOpening()

Hopefully this will be fixed in next version*

## Issue Categories

 - [ ] Bug

## Version Information

 - [ ] NuGet Package *4.0.270*
 - [ ] Build From *Master* branch, Commit *791a1ec954d762647*

**Comment by mariodivece** [comment]
This is by design. `Source` is a dependency property, and as such can only be accessed or set from the dispatcher thread that created it. The thread that created it is simply the GUI thread in this case as this is a WPF control. How about instead of changing internal library calls, you simply call the `Dispatcher.BeginInvoke` inside your code-behind, and within this invoke, set the Source property?
Pro Tip: You may ask: how do I get a reference to the proper dispatcher object? Simple! `MyFFmeControl.Dispatcher` will do the trick.

Please reopen if you have further questions.

**Comment by mariodivece** [comment]
what happens if you use the latest commit and slightly change your code to:
```csharp
var source = Uri(mediaElement.CameraState.Camera.StreamUri);
await MediaPlayer.Dispatcher.BeginInvoke(() => {MediaPlayer.Source = source; });
```

**Comment by Elchzone** [comment]
Hi. I've had a closer look at the bug my colleague has posted and I found out, that the bug is raised when we use the following namespace
`xmlns:i="clr-namespace:System.Windows.Interactivity;assembly=System.Windows.Interactivity"`

in this namespace you can build eventTriggers that call commands in a viewMode. You can do this to adhere more to MVVM principles. Example:

```
<ffme:MediaElement x:Name="Media" Background="Gray" LoadedBehavior="Play" UnloadedBehavior="Manual">
            <i:Interaction.Triggers>
                <i:EventTrigger EventName="MediaOpening">
                    <i:InvokeCommandAction Command="{Binding Path=MediaOpeningCommand, Mode=OneWay}" />
                </i:EventTrigger>
            </i:Interaction.Triggers>
</ffme:MediaElement>
```

The MediaOpeningCommand is really a standard command and has actually nothing to do with the raised exception. In fact, even if the binding for the command failed, the Exception is raised. 
So as soon, as such a construct is used, using the `Media.Open()` or `Media.Source` members (e.g. in the Codebehind) will raise the exception.
The exception can be caught with the Media_Failed event. 
The stacktrace is consistent with the initally posted stack trace.

Important: This construct worked totally fine in 2.6.0 and broke with 2.7.0. 
I tried to track down the causing change, but I'm not quite sure if it can be found in this commit:

https://github.com/unosquare/ffmediaelement/commit/55acef6f4c3c50340aeac4770ec0ebe7e6b95497#diff-93f94be4c7a3bfd77c9c41f0d4de2fb0

**Comment by mariodivece** [comment]
Sorry, this is an extremely complex control and I am unable to troubleshoot with very specific project code. Filing a bug here or on the Windows.Interactivity project would be essentially as misleading as the other. I can't help if you can't find the specific problem.
