### ISSUE TITLE
How to tell if hardware render is active

### ISSUE THREAD

**Issue by manity42** [unosquare/ffmediaelement#322]
# Issue Title (How to tell if hardware render is active)

*Please enter a general description for the issue. Delete sections that are not relevant and provide additional sections if necessary.*

## Issue Categories

 - [ ] Question

## Version Information
 - [ ] NuGet Package *2018.9.24.25313*

## Steps to Reproduce

 1. Download and build Sample FFME sample files and play h264 video
 2. Load and play same h264 video in VLC or WMP

## Expected Results
I would expect there to be no difference in the "smoothness" of playback between these media players and FFME. But it seems to me both WMP and VLC play the video smoother than FFME which is  just a tiny bit jumpier, not noticeable unless you have seen it played before or play them side by side. My question is how do you tell if FFME is using hardware rendering. In the sample files media player you generously provide the video renderer is shown as blank.  Is there any idea or suggestion i can try to get this ME replacement (which i think is awesome) to play back just a bit smoother ? i have tried several files and can so far only notice it on a H264. The CPU load using your sample application is very very low to almost not register. Its just does not play quite as smooth. All files and apps tested on the same PC and also on different PC together.

![image](https://user-images.githubusercontent.com/39360067/52838807-d72fc700-312e-11e9-9523-7097112e46e9.png)

**Comment by mariodivece** [comment]
There are additional CPU improvements coming with a new worker model. A couple of things:
1. The Video Accelerator field refers to the video **decoding** accelerator. The renderer is always via the WPF subsystem which involves transferring the decoded frame from the GPU (if Video Accelerator is being used) to the CPU accessible RAM. Then, since the frames come in proprietary GPU pixel format, I need to convert it to BGRA (standerd in WPF) using FFmpeg and finally write the compatible picture on to a WPF surface -- which in turns may or may not transfer the picture to the GPU again for WPF rendering. In short, it is certainly a round trip but it's difficult to tell WPF to render a picture directly stored in the GPU to avoid these data exchanges. If you find out a method of doing this, please let me know -- I tried very hard to find it but could not. Someone suggested an implementation quite some time ago but it only worked for a specific type of GPU -- something that I can't do in a library like this one.
2. I am testing with a 60 FPS file, side by side with VLC and I can't notice the smoothness problem you are seeing... Any way you can provide a sample file?
3. In your screenshot, it is strange that Video **decoding** Accelerator is empty given it is an h.264 file. What video card do you have?
4. Could you test the app using the latest commit on the `better-workers-2` branch and let me know if that helps with the smoothness issue?

**Comment by manity42** [comment]
I will try the latest commit as you suggest. please don't close this issue too soon.
I will try some more testing and see if i can derive more information.

**Comment by mariodivece** [comment]
Yeah, looking forward to your comments!

**Comment by manity42** [comment]
I have downloaded the latest version and tried comparing to again to the same H264 video playing in vlc or WMP. I tried it on 2 different machines. This time at the video renderer comes up as cuda.
I don't know it its just me but it does seem this control plays just the tinyest bit less smoother on parts where the motion is slow and gradual. But in truth I don't think its worth worrying about if no one else has mentioned it. likely its an issue with my media file or something like that. regardless its a great control. You might as well close this issue off. I cant provide anymore information on this item.  I expect its something to do with the media file itself.
