### ISSUE TITLE
Approach for synchronizing multiple videos

### ISSUE THREAD

**Issue by kealist** [unosquare/ffmediaelement#350]
# Approach for synchronizing multiple videos

I am working on synchronously playing multiple (5 at this time) video RTSP streams (local network) that have the same length.  I have a few questions related to this.  I know these are more conceptual but would appreciate feedback.   

1. In your opinion do you think it would be possible to do a frame perfect synchronization or would I be better off going with a lower level solution?  Based on the diagram on the readme, it looks like the MediaContainer and MediaEngine with multiple players could be put together to develop something like this, but wanted to ask your thought about it. 

2. I have tried one simple method of synchonizing video which is to have timed events and compare the position of the videos and seek a video if it is outside some threshold of what it should be.  This generally doesn't work because of the seek time varies from very fast to taking more than 2 seconds to complete.  Could be related to cache/amount of video downloaded.  

3.  Another thought I have is to change playback speed to have videos catch up to where they need to be if outside of a threshold as well.  This is going to be my next attempt

4. Is it easy to increase the cache size? Or a way to increase the rate at which things are downloaded.  The description of `PacketReadingWroker` in the Readme says this is set to 1 second at a time.

Thank you.

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x] Question
 - [ ] Not sure

**Comment by mariodivece** [comment]
1. you could try by setting up an external Diagnostics stopwatch and try to call seek on the MediaElements that are not within a given threshold -- from the sounds of comment number 2 you are already trying this. Since this usage scenario is outside the scope of this project, you could certainly go with a low level solution that suits your needs.

2. Have you tried also pausing (await Pause() the videos and then playing (await Play()) when all of them are within range?

3. Sure... that's one approach that could work

4. You can increase the block cache but the packet reading worker cache is fixed for seekable streams. Check out: https://github.com/unosquare/ffmediaelement/blob/ad7b361128444c0ee24c1a877d885ba836088e25/Unosquare.FFME.Common/Engine/MediaOptions.cs#L122
