### ISSUE TITLE
Stop and seek frame, then played few frame.

### ISSUE THREAD

**Issue by longlongago-k** [unosquare/ffmediaelement#360]
# Stop and seek frame, then played few frame.
## Issue Categories

 - [x] Bug
 - [ ] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information

 - [x] NuGet Package 4.1.280
 - [x] Build From Master branch, Commit e66028d5
 - [x] VS version: Visual studio 2017 community
## Steps to Reproduce
I updated nuget package from 4.0.270 to 4.1.280.
I tried my application or sample app in the master branch.
My application has seek list which has time, thumbnail, comment. User can seek video by clicking seek list. 

When seek by time, then video played few frames before seek finished.
(approximately 0.5-1.0 seconds played)

 1.  Open video by sample app.
 2.  Play and Pause.
 3.  Seek video by seek bar.

## Expected Results

 - Change video frame from current frame to seek frame.

**Comment by mariodivece** [comment]
This is by design. exact frame time seeking requires seeking to a P frame previous to the location of the desired position and decode frames moving forward to the desired time. The new package shows you the frames to give the illusion of a more fluid seek operation. Previous versions did not render such frames preventing immediate visual feedback to the user.

I have added a new `MediaOption` to disable this effect. In the next version you will be able to set:
`e.MediaOptions.IsFluidSeekingDisabled = true`

**Comment by longlongago-k** [comment]
Thank you for the consideration.
As the result, if user seek to I frame(or key frame), just move from current frame to seek frame without transition frame (P frame). Otherwise, library need to decode some P frame before desired frame which user seek. We can choose the behavior by new option whether user can see _decoding P frame_ or not.

In the future, can FFME support per key frame seeking?

**Comment by mariodivece** [comment]
you are correct, the new option is already available in the `uwp` branch which requires VS 2019 preview
