### ISSUE TITLE
Opt-In Hardware Decoding

### ISSUE THREAD

**Issue by gemelo-hh** [unosquare/ffmediaelement#392]
# or how to speed this great medialement

In the features overview you wrote: "Opt-in hardware decoding acceleration via devices or via codecs."

Can you describe, how to do this?

In general, your control works great. But CPU Power increases highly, especially compared to e.g. VLC Player playing the same video.

We reduced the max framerate to 20, which works fine:
         `   m_Media.RendererOptions.VideoRefreshRateLimit = 20;`

But we needed a higher framerate.

I saw your solution at Media_MediaOpening:
https://github.com/unosquare/ffmediaelement/issues/69

With that solution I have the problem, that 

`videoStream.HardwareDevices`

contains no elements. Does that mean, that hardware acceleration is not supported?

Best regards and thank you again for your great work!

Thies

## Issue Categories

 - [x] Question

## Version Information

 - [x] NuGet Package 4.1.300

**Comment by mariodivece** [comment]
Correct, if there is no hardware devices then there is no hardware device in your system that can decode the video codec. The reason why CPU usage is higher in FFME than say, VLC is because of the memcpy round trips it makes. If you find a way to put the decoded images into a DirectX or OpenGL surface and render it directly on a WPF Bitmap or control, it would eliminate the round trips.

Please see the explanation here:
https://github.com/unosquare/ffmediaelement/issues/244#issuecomment-395829949

**Comment by mariodivece** [comment]
Closing this issue until firther feedback is provided.
