### ISSUE TITLE
Why does demo code not set explicit VideoHardwareDevice for release build

### ISSUE THREAD

**Issue by manity42** [unosquare/ffmediaelement#401]
# Issue Title (*Why does demo code not set explicit VideoHardwareDevice for release build*)

In your sample code in the OnMediaOpeningEvent you have this

 if (videoStream.FPS <= 30)
      {
       foreach (var deviceType in deviceCandidates)
          {
           var accelerator = videoStream.HardwareDevices.FirstOrDefault(d => d.DeviceType == deviceType);
            if (accelerator == null) continue;
            if (Debugger.IsAttached)
                  e.Options.VideoHardwareDevice = accelerator;
              break;
            }
       }

Specifically this item
  if (Debugger.IsAttached)
        e.Options.VideoHardwareDevice = accelerator;

Why do you only set the accelerator explicitly when the Debugger is attached ?
Should it not be tested for/set always, otherwise the release build would default to the lowest available which would be i think "DXVA2"

Am i missing something ?

Awesome control thanks so much.

## Issue Categories

 - [X] Question

## Version Information

 - [4.13 ] NuGet Package *Enter Version Number Here*

**Comment by mariodivece** [comment]
I personally do not recommend using hardware decoding. It tends to seek more slowly due to picture round trips and also tends to have lower picture quality. The only case where I would recommend hardware decoding is when the codec is tough on the CPU like hi-res H.265. I enable hardware decoding in the sample app for testing purposes.

Further explanations are available in issue #392 and #244
