### ISSUE TITLE
Issue while loading FFmpeg

### ISSUE THREAD

**Issue by CyberSinh** [unosquare/ffmediaelement#404]
*Better error handling while loading FFmpeg*

## Issue Categories

 - Bug

## Version Information

 - Commit e5f8b3e4

## Bug report

Something went wrong while loading FFmpeg at a user's premises. Here is the stack trace:
```
System.Runtime.InteropServices.MarshalDirectiveException: "No se pueden calcular las referencias de 'parameter #3': Combinación de tipos administrado y no administrado no válida (los parámetros y tipos de valor devueltos String deben estar emparejados con LPStr, LPWStr, LPTStr, BStr, TBStr, VBByRefStr o AnsiBStr)."

-> System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegateInternal(Delegate d)
-> System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(Delegate d)
-> FFmpeg.AutoGen.av_log_set_callback_callback_func.op_Implicit(av_log_set_callback_callback func)
-> FFmpeg.AutoGen.FFInterop.Initialize(String overridePath, Int32 libIdentifiers)
-> Unosquare.FFME.Library.LoadFFmpeg()
-> Unosquare.FFME.Commands.CommandManager.CommandOpenMedia(IMediaInputStream inputStream, Uri streamUri)
-> Unosquare.FFME.Commands.CommandManager+<>c__DisplayClass14_0.<OpenMediaAsync>b__0()
-> Unosquare.FFME.Commands.CommandManager+<>c__DisplayClass47_0.<ExecuteDirectCommand>b__0()
```

With the slightest exception thrown in `FFInterop.Initialize()`, ffmediaelement forces `m_IsInitialized` to `false`. However, the exception mentioned above does not seem to have compromised the loading of FFmpeg libraries, since a new call to `FFInterop.Initialize()` failed because of "Library avutil was already loaded":
```
System.InvalidOperationException: "Library avutil was already loaded."

-> FFmpeg.AutoGen.FFLibrary.Load(String basePath)
-> FFmpeg.AutoGen.FFInterop.Initialize(String overridePath, Int32 libIdentifiers)
-> Unosquare.FFME.Library.LoadFFmpeg()
-> Unosquare.FFME.Commands.CommandManager.CommandOpenMedia(IMediaInputStream inputStream, Uri streamUri)
-> Unosquare.FFME.Commands.CommandManager+<>c__DisplayClass14_0.<OpenMediaAsync>b__0()
-> Unosquare.FFME.Commands.CommandManager+<>c__DisplayClass47_0.<ExecuteDirectCommand>b__0()
```

Thanks.

**Comment by mariodivece** [comment]
it should now try to continue loading the libraries. I now prevent calling the Load operation if the library has been loaded already.

**Comment by CyberSinh** [comment]
Thanks Mario. Do the patch fix both exceptions above or just the `InvalidOperationException` one?

**Comment by mariodivece** [comment]
Hey @CyberSinh I am unsure of what you mean by fixing exceptions. What would the ideal expected result be, according to your view?

**Comment by CyberSinh** [comment]
I am not an expert in PInvoke but it seems that `MarshalDirectiveException ', which derives from` SystemException', is a programming issue that should not occur in production (or if it cannot be avoid, at least cleanly managed).

**Comment by mariodivece** [comment]
The exception you see is because there is a method that does not match in one or another way the signature it expects from the C library. The solution is to make sure the build of FFmpeg in use is compatible with that published in FFmpeg.Autogen. If you are having marshaling exceptions and you are using compatible libraries, then you should post the issues on the FFmpeg.Autogen project instead as this is where the interop libraries are maintained.

**Comment by ryanmcbrideusf** [comment]
I ran into this same issue recently and it was only happening on one PC in particular. It turns out that the problem was the version of .NET that was installed. I was trying to run my application on a PC which only had 4.6.2 installed, but after installing 4.7 it no longer crashes.

More specifically, FFmpeg.Autogen seems to use a specific enum value (UnmanagedType.LPUTF8Str) which did not exist prior to .NET 4.7.

**Comment by mariodivece** [comment]
Related Issue: https://github.com/Ruslan-B/FFmpeg.AutoGen/issues/96
