### ISSUE TITLE
Allow more than one subtitle stream processing

### ISSUE THREAD

**Issue by Neocriss** [unosquare/ffmediaelement#419]
# Allow more than one subtitle stream processing

*It's feature request.*

I am learning English and I need the ability to read more than one subtitle stream at a time. At least one stream in English and one stream in my native language. 

But at 'OnMediaChanging' event I can specify only one subtitle stream. From other side all components of 'FFME.MediaElement' are closed for extension.

Make it possible to receive text in 'RenderingSubtitles' event from different subtitles without switching between streams.

**Comment by mariodivece** [comment]
Sorry, the control only allows 1 stream per component type by design. The alternative is to look at the `Utilities.LoadBlocks` code and implement your own. It's used in preloading subtitles from a separate URL here:
`MediaCore.PreloadedSubtitles = Utilities.LoadBlocks(subtitlesUrl, MediaType.Subtitle, MediaCore);`

Exposing this functionality as a static method would force me to expose internal classes that are not meant for the end user as they are difficult to work with and would create more questions than help.

**Comment by Neocriss** [comment]
Mario, thanks for the answer. But this functionality is marked as internal.

This:
`internal static MediaBlockBuffer LoadBlocks(string mediaSource, MediaType sourceType, ILoggingHandler parent)`
and this:
`internal interface ILoggingHandler`
:'(
