### ISSUE TITLE
Setting FFmpegLoadModeFlags to video only causes library not to load

### ISSUE THREAD

**Issue by Arestihub** [unosquare/ffmediaelement#429]
Setting FFmpegLoadModeFlags to video only causes library not to load

When setting FFmpegLoadModeFlags to video only there's an error after compiling and running the program saying it could't load swresample-3.dll. LibSWResample shouldn't be included at all when loading video only if I am not mistaken (https://github.com/unosquare/ffmediaelement/blob/f1aa759b98a62e8f7ecfe6ddf5e4162b20a4d4a7/Unosquare.FFME/FFmpeg/FFmpegLoadMode.cs)

When loading with the default load mode everything loads just fine. Minimumfeatures also works. All dlls are present in my ffmpeg folder at all times, no matter which load mode flags I try to use.

## Issue Categories

 - [x ] Bug
 - [ ] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information

 - [x ] NuGet Package 4.1.310
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Steps to Reproduce

 1. Set Library.FFmpegLoadModeFlags = FFmpegLoadMode.VideoOnly
 2. Try to load FFmpeg

## Expected Results

 FFmpeg should load with LibAVCodec, LibAVFormat, LibAVUtil and LibSWScale
 
## Sample Code

```csharp
            Library.FFmpegDirectory = @"c:\ffmpeg";
            Library.FFmpegLoadModeFlags = FFmpegLoadMode.VideoOnly;
            Library.LoadFFmpeg();
```

**Comment by mariodivece** [comment]
Related to #414 

This will be highly dependent on your ffmpeg build. For example, if LibAVCodec or LibAVFormat depend on SWResample because they contain audio codecs that need it, your library set won't load correctly. My advice would be to either build ffmpeg without the avresample dependency or simply come up with a flag combination that works for your build as in the documentation provided here (functionality will be available in the next NuGet release):
https://github.com/unosquare/ffmediaelement/blob/3e1f2d4662f73ecedf23223d279f7035c622736d/Unosquare.FFME.Windows.Sample/App.xaml.cs#L26
