### ISSUE TITLE
Unable to use pipe://. Are pipes supported?

### ISSUE THREAD

**Issue by AndrewBatta** [unosquare/ffmediaelement#469]
I was searching for a media player that supports named pipes and I noticed that it was mentioned as something that might be supported in the future, but I'm not sure if it was implemented. Are named pipes supported and if so, can you share an example?

**Comment by mariodivece** [comment]
Sure! The key here is to implement IMediaInputStream as done in the sample app:
https://github.com/unosquare/ffmediaelement/blob/7903074d6655ed552952ad3e2fb27a1746ce4c1a/Unosquare.FFME.Windows.Sample/Foundation/FileInputStream.cs#L37

Instead of a file stream you would use the following class:
https://docs.microsoft.com/en-us/dotnet/api/system.io.pipes.namedpipeclientstream?view=netframework-4.8

Then, when opening the media, instead of passing a Uri, just create an instance of your IMediaInputStream. For Example:

```csharp
await media.Open(new MyPipeReader("servernamehere", "pipenamehere"));
```
