### ISSUE TITLE
Play through Decklink card output

### ISSUE THREAD

**Issue by netwolf911** [unosquare/ffmediaelement#509]
# Issue Title (*Play through Decklink card output*)

Hi,

I found 2 case about external device usage with FFME, but these talk about capture only.
I built ffmpeg with decklink option and it works in command line.
Question is. Is it possible use with FFME? It could be a easier way.
Or maybe i could use media engine, where create the frame packed for the desktop and after it send to the decklink output with deklink API.
Could you help me somebody or do you have any knowledge or advice?

thx,
Joe 

## Issue Categories

 - [ ] Bug
 - [x ] Feature Request
 - [x] Question
 - [ ] Not sure

**Comment by Mitra-M** [comment]
Hi,
This is a great wrapper for FFplay but not FFmpeg , and doesn't have all the FFmpeg side features.  (There is no option for card output in the FFplay , I think)

> Or maybe i could use media engine, where create the frame packed for the desktop and after it send to the decklink output with deklink API.

I don't think it's a good idea, because performance issue .  The best option for such devices is to use API in c / c ++ native codes. (Don't waste your time)

**Comment by mariodivece** [comment]
@Mitra-M is right. FFME will not solve your specific case -- it's outside the scope of this project.
