### ISSUE TITLE
Adaptive buffering for semi-realtime streams (MJPEG)

### ISSUE THREAD

**Issue by adam8797** [unosquare/ffmediaelement#72]
I'd like to use this media element to play an MJPEG stream from over a network connection. However, this is a real-time application, and the buffer delay of 1 second just wont do. 

I've been trying to find a way to disable the buffer. There are some suggestions [here](https://trac.ffmpeg.org/wiki/StreamingGuide#Latency), but they just apply to plain FFMPEG.

Any ideas?

**Comment by mariodivece** [comment]
Hmmm... let me check this issue. This one seems rather important... I will need to find useful mjpeg streams as I have not tested them. If you could point some out, I could use them!

**Comment by adam8797** [comment]
I've been using this project to test. It just hosts an mjpeg stream of the desktop.

https://www.codeproject.com/Articles/371955/Motion-JPEG-Streaming-Server

I had to run it from source, because its a little finicky to get started. But once you get it running, it keeps going fine.

Thanks for looking into this!

**Comment by mariodivece** [comment]
I have improved mjpeg streaming smoothness! Now, when testing with the desktop streaming server sample you provided, it takes a couple of seconds to open the stream and then it just become really close to realtime. If I connect to an mjpeg stream of an IP camera, the stream opens immediately and the response is also really close to realtime (~100ms delay). For both tests I see the same results as using ffplay.exe
Can you test now with the latest commit and let me know if you see what you are expecting please?

**Comment by adam8797** [comment]
Thank you so much!

It will be difficult for me to test it in the next few days, but I'll get back to you ASAP with the results.

**Comment by mariodivece** [comment]
Ok, thanks. Let me know how it goes. My MJPEG streams play very well. There are some debug messages but these make sense. For some reason MJPEG streams are decoded by ffmpeg at 25 fps always -- I guess timing info is not available on the format? I stream at 10 fps from an IP camera and fps is set to 25 from the stream always, so FFME thinks it is going out of sync and re-buffers. I changed the code so that this re-buffering does not make the display stutter.

**Comment by adam8797** [comment]
I'm still getting the buffering. What did your stream URL look like? I'm just using the sample application with the url:

`http://129.25.217.182:8080/?action=stream_0`

If I try adding a fake url param (to give it a .jpg extension):

`http://129.25.217.182:8080/?action=stream_0&file=fake.jpg`

I just get a black screen.

Any ideas?

**Comment by mariodivece** [comment]
Are you by any chance running this on windows 7? This sounds related to issue #75

**Comment by adam8797** [comment]
Nope. Windows 10. 

It's definitely still buffering, as the buffer bar is filling.

**Comment by mariodivece** [comment]
Do you still see it skipping frames and stuttering? Or is the problem just the fact that the buffering bar keeps changing?

**Comment by adam8797** [comment]
I'm sorry if I wasn't totally clear.

The problem is **that** it is buffering. There are no skipped frames or stuttering. I just need a low-latency video stream, and a buffer of 1 second is too much. We're attempting to use this to pilot an ROV type vehicle, so reducing latency is the primary focus.

**Comment by mariodivece** [comment]
Ah... I see... FFME buffers whatever it can and UP TO certain amount of bytes but it renders as soon as it possibly can. In my case with the MJPEG streamer sample, I see a delay of about 200ms. With my IP camera I see a delay of around 100ms. What happens is that FFMPEG internally decides how much date is pre-buffered before it can read frames from packets. There are 2 options in the MediaOpening event that you can change:
https://github.com/unosquare/ffmediaelement/blob/master/Unosquare.FFME/MediaOptions.cs#L73
https://github.com/unosquare/ffmediaelement/blob/master/Unosquare.FFME/MediaOptions.cs#L80

Try setting these to a minimum and see if it improves. When I change these parameters, some streams loose audio or have incorrect frame data because it prevents ffmpeg from probing enough of the stream to detect stream formats and other features.

If fiddling with these options doesn't work, try opening the stream with ffplay.exe and try the different arguments. If you get it to the point where you can see it almost realtime, send me the ffplay arguments and I will implement them as properties in the MediaOptions class so you are able to set them also in FFME.

**Comment by adam8797** [comment]
Sounds good. I'll do some experimenting and get back to you.

Thanks for your help here, I appreciate it.

**Comment by mariodivece** [comment]
Yep no problem. Here's more info:
https://trac.ffmpeg.org/wiki/StreamingGuide#Testinglatency

**Comment by kjeremy** [comment]
@mariodivece Which options are those in `MediaOptions.cs`?  They point to the wrong lines now and I'm running into something similar.

**Comment by kjeremy** [comment]
@adam8797 Did you solve this? I have a similar issue with an h264 stream.

**Comment by mariodivece** [comment]
```
        /// <summary>
        /// Gets or sets the maximum duration to be analyzed before ifentifying stream information.
        /// In realtime streams this can be reduced to reduce latency (i.e. TimeSpan.Zero)
        /// </summary>
        public TimeSpan MaxAnalyzeDuration { get; set; }

        /// <summary>
        /// Gets or sets the amount of bytes to probe before getting the stram info
        /// In realtime streams probesize can be reduced to reduce latency.
        /// Minimum value is 32.
        /// </summary>
        public int ProbeSize { get; set; }
```

**Comment by adam8797** [comment]
Sorry, I can’t say that I did. The closest I got was by using VLC.Net (which honesty never seemed very stable, and had problems of its own).

We ended up redesigning our app as a web app, and let the browser handle the video streams. 

Sorry I couldn’t help. 

Thanks,
Adam Schiavone

**Comment by mariodivece** [comment]
Maybe I need to add seeking functionality to force and advance the clock on the real-time buffer. Do you guys have any other comments?

**Comment by mariodivece** [comment]
I am getting immediate sub-100ms response from both, the sample desktop streaming app and an IP camera with my latest commit. Closing this issue. Reopen if needed.
