### ISSUE TITLE
Invalid Url: Error for some filenames

### ISSUE THREAD

**Issue by VahedCivil** [unosquare/ffmediaelement#99]
Hi
When I open some filename , It take follow exception:
![image](https://user-images.githubusercontent.com/26754783/31692870-807f534e-b3a8-11e7-8c24-2ed78a648513.png)
But after renaming it, It will be show video.
What's problem with with some filename especially arabic chars?

**Comment by Vasilich** [comment]
post exact filename, what leads to troubles, together with full path, here, so we can test.

**Comment by mariodivece** [comment]
Any feedback here before I close this down?

**Comment by xupefei** [comment]
A file name contains special Unicode characters e.g. `ABC・DEF.mp3`  will surface the problem.
Btw, it seems like a bug of FFmpeg:
https://ffmpeg.org/pipermail/libav-user/2012-October/002808.html
https://ffmpeg.org/pipermail/ffmpeg-devel/2012-April/123449.html

**Comment by mariodivece** [comment]
Correct @xupefei I really cannot do anything about this one. Closing.

**Comment by xupefei** [comment]
To someone who came here because of the similar problem:

FFmpeg's `avformat_open_input` does not handle Unicode file name correctly (there exist a [bug report](https://trac.ffmpeg.org/ticket/819) ... and it's opened for 6 years!)

Fortunately, there is still one workaround before modifying FFmpeg source codes: **use the old 8.3 filename**. The [`GetShortPathName` API](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364989(v=vs.85).aspx) will help you.
